export const TABLE_SCHEMAS: Record<string, string> = {
  projects: `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    name TEXT NOT NULL,
    client_id TEXT,
    status TEXT NOT NULL DEFAULT 'idea',
    discipline_tags TEXT NOT NULL DEFAULT '[]',
    start_date TEXT,
    target_date TEXT,
    completed_date TEXT,
    estimated_hours REAL,
    actual_hours REAL DEFAULT 0,
    budget REAL,
    notes TEXT,
    cover_photo_url TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  inventory_items: `CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    name TEXT NOT NULL,
    master_category TEXT NOT NULL,
    sub_category TEXT,
    sku TEXT,
    supplier_name TEXT,
    supplier_url TEXT,
    quantity REAL NOT NULL DEFAULT 0,
    unit TEXT NOT NULL,
    unit_cost REAL,
    location TEXT,
    low_stock_threshold REAL,
    notes TEXT,
    photo_url TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  inventory_deductions: `CREATE TABLE IF NOT EXISTS inventory_deductions (
    id TEXT PRIMARY KEY,
    inventory_item_id TEXT NOT NULL,
    project_id TEXT,
    quantity_deducted REAL NOT NULL,
    unit TEXT NOT NULL,
    notes TEXT,
    deducted_at TEXT NOT NULL DEFAULT (datetime('now')),
    user_id TEXT
  )`,
  clients: `CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    full_name TEXT NOT NULL,
    company TEXT,
    email TEXT,
    phone TEXT,
    preferred_contact TEXT,
    billing_address TEXT,
    shipping_address TEXT,
    tags TEXT NOT NULL DEFAULT '[]',
    source TEXT,
    notes TEXT,
    internal_rating INTEGER,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  journal_entries: `CREATE TABLE IF NOT EXISTS journal_entries (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    entry_date TEXT NOT NULL DEFAULT (date('now')),
    title TEXT,
    body_rich_text TEXT,
    discipline_tags TEXT NOT NULL DEFAULT '[]',
    project_ids TEXT NOT NULL DEFAULT '[]',
    hours_logged REAL,
    mood TEXT,
    machine_used TEXT,
    photo_urls TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  quotes: `CREATE TABLE IF NOT EXISTS quotes (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    client_id TEXT NOT NULL,
    project_id TEXT,
    quote_number TEXT NOT NULL,
    valid_until TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    discount_type TEXT,
    discount_value REAL,
    tax_rate REAL,
    notes_client TEXT,
    notes_internal TEXT,
    terms TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  quote_line_items: `CREATE TABLE IF NOT EXISTS quote_line_items (
    id TEXT PRIMARY KEY,
    quote_id TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  invoices: `CREATE TABLE IF NOT EXISTS invoices (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    quote_id TEXT,
    client_id TEXT NOT NULL,
    project_id TEXT,
    invoice_number TEXT NOT NULL,
    issue_date TEXT NOT NULL DEFAULT (date('now')),
    due_date TEXT,
    payment_terms TEXT NOT NULL DEFAULT 'net_30',
    status TEXT NOT NULL DEFAULT 'draft',
    discount_type TEXT,
    discount_value REAL,
    tax_rate REAL,
    notes_client TEXT,
    notes_internal TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  invoice_line_items: `CREATE TABLE IF NOT EXISTS invoice_line_items (
    id TEXT PRIMARY KEY,
    invoice_id TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  invoice_payments: `CREATE TABLE IF NOT EXISTS invoice_payments (
    id TEXT PRIMARY KEY,
    invoice_id TEXT NOT NULL,
    amount REAL NOT NULL,
    payment_method TEXT,
    payment_date TEXT NOT NULL DEFAULT (date('now')),
    notes TEXT
  )`,
  calculator_results: `CREATE TABLE IF NOT EXISTS calculator_results (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    project_id TEXT,
    module TEXT NOT NULL,
    calculator_type TEXT NOT NULL,
    inputs_json TEXT NOT NULL,
    outputs_json TEXT NOT NULL,
    label TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  saved_recipes: `CREATE TABLE IF NOT EXISTS saved_recipes (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    module TEXT NOT NULL,
    recipe_type TEXT NOT NULL,
    name TEXT NOT NULL,
    config_json TEXT NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  wood_species: `CREATE TABLE IF NOT EXISTS wood_species (
    id TEXT PRIMARY KEY,
    common_name TEXT NOT NULL,
    botanical_name TEXT,
    janka_hardness INTEGER,
    density_lbs_ft3 REAL,
    tangential_shrinkage REAL,
    radial_shrinkage REAL,
    typical_uses TEXT,
    finishing_notes TEXT,
    toxicity_warnings TEXT,
    price_tier TEXT,
    domestic INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  laser_materials: `CREATE TABLE IF NOT EXISTS laser_materials (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  material_name TEXT NOT NULL,
  brand TEXT,
  thickness_mm REAL NOT NULL,
  operation TEXT NOT NULL,
  power_pct REAL NOT NULL,
  speed_mms REAL NOT NULL,
  passes INTEGER NOT NULL DEFAULT 1,
  ppi_frequency INTEGER,
  focus_offset_mm REAL DEFAULT 0,
  air_assist INTEGER NOT NULL DEFAULT 1,
  laser_wattage INTEGER NOT NULL,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  cnc_materials: `CREATE TABLE IF NOT EXISTS cnc_materials (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  material_name TEXT NOT NULL,
  sfm_low REAL NOT NULL,
  sfm_high REAL NOT NULL,
  chipload_json TEXT NOT NULL,
  max_doc_pct REAL NOT NULL,
  coolant TEXT NOT NULL DEFAULT 'none',
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  cnc_tools: `CREATE TABLE IF NOT EXISTS cnc_tools (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  tool_type TEXT NOT NULL,
  cut_direction TEXT,
  diameter_in REAL NOT NULL,
  shank_diameter_in REAL,
  flutes INTEGER NOT NULL,
  tool_material TEXT NOT NULL,
  max_doc_in REAL,
  vbit_angle REAL,
  tip_width_in REAL,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  cnc_tool_usage: `CREATE TABLE IF NOT EXISTS cnc_tool_usage (
  id TEXT PRIMARY KEY,
  tool_id TEXT NOT NULL,
  project_id TEXT,
  minutes_used REAL NOT NULL,
  notes TEXT,
  logged_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  user_settings: `CREATE TABLE IF NOT EXISTS user_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  )`,
  printer_profiles: `CREATE TABLE IF NOT EXISTS printer_profiles (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  build_volume_x REAL NOT NULL,
  build_volume_y REAL NOT NULL,
  build_volume_z REAL NOT NULL,
  nozzle_diameter REAL NOT NULL DEFAULT 0.4,
  max_volumetric_flow REAL,
  extruder_type TEXT NOT NULL DEFAULT 'bowden',
  bowden_length_mm REAL,
  steps_per_mm_x REAL,
  steps_per_mm_y REAL,
  steps_per_mm_z REAL,
  steps_per_mm_e REAL,
  default_speed_mms REAL DEFAULT 50,
  default_travel_mms REAL DEFAULT 150,
  is_active INTEGER NOT NULL DEFAULT 0,
  source TEXT NOT NULL DEFAULT 'user',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  knife_steels: `CREATE TABLE IF NOT EXISTS knife_steels (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  harden_temp_f INTEGER NOT NULL,
  soak_minutes INTEGER NOT NULL,
  quench_medium TEXT NOT NULL,
  temper_low_f INTEGER NOT NULL,
  temper_high_f INTEGER NOT NULL,
  rockwell_low REAL NOT NULL,
  rockwell_high REAL NOT NULL,
  normalize_temp_f INTEGER,
  normalize_cycles INTEGER DEFAULT 3,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  chat_messages: `CREATE TABLE IF NOT EXISTS chat_messages (
  id TEXT PRIMARY KEY,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  context_json TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  subscription: `CREATE TABLE IF NOT EXISTS subscription (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
)`,
  printing_filaments: `CREATE TABLE IF NOT EXISTS printing_filaments (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  print_temp_low INTEGER NOT NULL,
  print_temp_high INTEGER NOT NULL,
  bed_temp_low INTEGER NOT NULL,
  bed_temp_high INTEGER NOT NULL,
  max_flow_rate REAL NOT NULL,
  density REAL NOT NULL,
  retraction_dist_bowden REAL NOT NULL,
  retraction_dist_direct REAL NOT NULL,
  retraction_speed REAL NOT NULL,
  cost_per_kg REAL,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
};

export const INDEX_SCHEMAS: string[] = [
  "CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status)",
  "CREATE INDEX IF NOT EXISTS idx_projects_client ON projects(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory_items(master_category)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventory_items(quantity, low_stock_threshold)",
  "CREATE INDEX IF NOT EXISTS idx_deductions_project ON inventory_deductions(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_deductions_item ON inventory_deductions(inventory_item_id)",
  "CREATE INDEX IF NOT EXISTS idx_journal_date ON journal_entries(entry_date)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_client ON quotes(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes(status)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_client ON invoices(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_due ON invoices(due_date)",
  "CREATE INDEX IF NOT EXISTS idx_calc_results_module ON calculator_results(module)",
  "CREATE INDEX IF NOT EXISTS idx_calc_results_project ON calculator_results(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_laser_materials_category ON laser_materials(category)",
  "CREATE INDEX IF NOT EXISTS idx_laser_materials_operation ON laser_materials(operation)",
  "CREATE INDEX IF NOT EXISTS idx_cnc_materials_category ON cnc_materials(category)",
  "CREATE INDEX IF NOT EXISTS idx_cnc_tools_type ON cnc_tools(tool_type)",
  "CREATE INDEX IF NOT EXISTS idx_cnc_tool_usage_tool ON cnc_tool_usage(tool_id)",
  "CREATE INDEX IF NOT EXISTS idx_printer_profiles_active ON printer_profiles(is_active)",
  "CREATE INDEX IF NOT EXISTS idx_printing_filaments_category ON printing_filaments(category)",
  "CREATE INDEX IF NOT EXISTS idx_knife_steels_category ON knife_steels(category)",
  "CREATE INDEX IF NOT EXISTS idx_chat_messages_created ON chat_messages(created_at)",
];

export function getTableNames(): string[] {
  return Object.keys(TABLE_SCHEMAS);
}
