export const TABLE_SCHEMAS: Record<string, string> = {
  projects: `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    name TEXT NOT NULL,
    client_id TEXT,
    status TEXT NOT NULL DEFAULT 'idea',
    discipline_tags TEXT NOT NULL DEFAULT '[]',
    start_date TEXT,
    target_date TEXT,
    completed_date TEXT,
    estimated_hours REAL,
    actual_hours REAL DEFAULT 0,
    budget REAL,
    notes TEXT,
    cover_photo_url TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  inventory_items: `CREATE TABLE IF NOT EXISTS inventory_items (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    name TEXT NOT NULL,
    master_category TEXT NOT NULL,
    sub_category TEXT,
    sku TEXT,
    supplier_name TEXT,
    supplier_url TEXT,
    quantity REAL NOT NULL DEFAULT 0,
    unit TEXT NOT NULL,
    unit_cost REAL,
    location TEXT,
    low_stock_threshold REAL,
    notes TEXT,
    photo_url TEXT,
    metadata TEXT DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  inventory_deductions: `CREATE TABLE IF NOT EXISTS inventory_deductions (
    id TEXT PRIMARY KEY,
    inventory_item_id TEXT NOT NULL,
    project_id TEXT,
    quantity_deducted REAL NOT NULL,
    unit TEXT NOT NULL,
    notes TEXT,
    deducted_at TEXT NOT NULL DEFAULT (datetime('now')),
    user_id TEXT
  )`,
  clients: `CREATE TABLE IF NOT EXISTS clients (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    full_name TEXT NOT NULL,
    company TEXT,
    email TEXT,
    phone TEXT,
    preferred_contact TEXT,
    billing_address TEXT,
    shipping_address TEXT,
    tags TEXT NOT NULL DEFAULT '[]',
    source TEXT,
    notes TEXT,
    internal_rating INTEGER,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  journal_entries: `CREATE TABLE IF NOT EXISTS journal_entries (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    entry_date TEXT NOT NULL DEFAULT (date('now')),
    title TEXT,
    body_rich_text TEXT,
    discipline_tags TEXT NOT NULL DEFAULT '[]',
    project_ids TEXT NOT NULL DEFAULT '[]',
    hours_logged REAL,
    mood TEXT,
    machine_used TEXT,
    photo_urls TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  quotes: `CREATE TABLE IF NOT EXISTS quotes (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    client_id TEXT NOT NULL,
    project_id TEXT,
    quote_number TEXT NOT NULL,
    valid_until TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    discount_type TEXT,
    discount_value REAL,
    tax_rate REAL,
    notes_client TEXT,
    notes_internal TEXT,
    terms TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  quote_line_items: `CREATE TABLE IF NOT EXISTS quote_line_items (
    id TEXT PRIMARY KEY,
    quote_id TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  invoices: `CREATE TABLE IF NOT EXISTS invoices (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    quote_id TEXT,
    client_id TEXT NOT NULL,
    project_id TEXT,
    invoice_number TEXT NOT NULL,
    issue_date TEXT NOT NULL DEFAULT (date('now')),
    due_date TEXT,
    payment_terms TEXT NOT NULL DEFAULT 'net_30',
    status TEXT NOT NULL DEFAULT 'draft',
    discount_type TEXT,
    discount_value REAL,
    tax_rate REAL,
    notes_client TEXT,
    notes_internal TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  invoice_line_items: `CREATE TABLE IF NOT EXISTS invoice_line_items (
    id TEXT PRIMARY KEY,
    invoice_id TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    quantity REAL NOT NULL DEFAULT 1,
    unit TEXT,
    unit_price REAL NOT NULL DEFAULT 0,
    line_total REAL NOT NULL DEFAULT 0,
    taxable INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0
  )`,
  invoice_payments: `CREATE TABLE IF NOT EXISTS invoice_payments (
    id TEXT PRIMARY KEY,
    invoice_id TEXT NOT NULL,
    amount REAL NOT NULL,
    payment_method TEXT,
    payment_date TEXT NOT NULL DEFAULT (date('now')),
    notes TEXT
  )`,
  calculator_results: `CREATE TABLE IF NOT EXISTS calculator_results (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    project_id TEXT,
    module TEXT NOT NULL,
    calculator_type TEXT NOT NULL,
    inputs_json TEXT NOT NULL,
    outputs_json TEXT NOT NULL,
    label TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  saved_recipes: `CREATE TABLE IF NOT EXISTS saved_recipes (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    module TEXT NOT NULL,
    recipe_type TEXT NOT NULL,
    name TEXT NOT NULL,
    config_json TEXT NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  wood_species: `CREATE TABLE IF NOT EXISTS wood_species (
    id TEXT PRIMARY KEY,
    common_name TEXT NOT NULL,
    botanical_name TEXT,
    janka_hardness INTEGER,
    density_lbs_ft3 REAL,
    tangential_shrinkage REAL,
    radial_shrinkage REAL,
    typical_uses TEXT,
    finishing_notes TEXT,
    toxicity_warnings TEXT,
    price_tier TEXT,
    domestic INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  )`,
  laser_materials: `CREATE TABLE IF NOT EXISTS laser_materials (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  material_name TEXT NOT NULL,
  brand TEXT,
  thickness_mm REAL NOT NULL,
  operation TEXT NOT NULL,
  power_pct REAL NOT NULL,
  speed_mms REAL NOT NULL,
  passes INTEGER NOT NULL DEFAULT 1,
  ppi_frequency INTEGER,
  focus_offset_mm REAL DEFAULT 0,
  air_assist INTEGER NOT NULL DEFAULT 1,
  laser_wattage INTEGER NOT NULL,
  notes TEXT,
  source TEXT NOT NULL DEFAULT 'built-in',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`,
  user_settings: `CREATE TABLE IF NOT EXISTS user_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  )`,
};

export const INDEX_SCHEMAS: string[] = [
  "CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status)",
  "CREATE INDEX IF NOT EXISTS idx_projects_client ON projects(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory_items(master_category)",
  "CREATE INDEX IF NOT EXISTS idx_inventory_low_stock ON inventory_items(quantity, low_stock_threshold)",
  "CREATE INDEX IF NOT EXISTS idx_deductions_project ON inventory_deductions(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_deductions_item ON inventory_deductions(inventory_item_id)",
  "CREATE INDEX IF NOT EXISTS idx_journal_date ON journal_entries(entry_date)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_client ON quotes(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_quotes_status ON quotes(status)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_client ON invoices(client_id)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_status ON invoices(status)",
  "CREATE INDEX IF NOT EXISTS idx_invoices_due ON invoices(due_date)",
  "CREATE INDEX IF NOT EXISTS idx_calc_results_module ON calculator_results(module)",
  "CREATE INDEX IF NOT EXISTS idx_calc_results_project ON calculator_results(project_id)",
  "CREATE INDEX IF NOT EXISTS idx_laser_materials_category ON laser_materials(category)",
  "CREATE INDEX IF NOT EXISTS idx_laser_materials_operation ON laser_materials(operation)",
];

export function getTableNames(): string[] {
  return Object.keys(TABLE_SCHEMAS);
}
